// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxWW6_bHmhWkmiETxlhLsA04SXWD_3zs',
    appId: '1:749691611072:web:6cba5fda2650f33753ca25',
    messagingSenderId: '749691611072',
    projectId: 'app-futebol-122ad',
    authDomain: 'app-futebol-122ad.firebaseapp.com',
    storageBucket: 'app-futebol-122ad.firebasestorage.app',
    measurementId: 'G-X6DB4ZMF5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKs-zdngvrs-soeR1kDBj74La6hPo8qk',
    appId: '1:749691611072:android:662b3965d9c4112553ca25',
    messagingSenderId: '749691611072',
    projectId: 'app-futebol-122ad',
    storageBucket: 'app-futebol-122ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqj-cQ5i_KmRUCNg7pWgUzQNcMwsOu0ZM',
    appId: '1:749691611072:ios:9fb90138ae20ea6f53ca25',
    messagingSenderId: '749691611072',
    projectId: 'app-futebol-122ad',
    storageBucket: 'app-futebol-122ad.firebasestorage.app',
    iosBundleId: 'com.example.appFutebol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJxWW6_bHmhWkmiETxlhLsA04SXWD_3zs',
    appId: '1:749691611072:web:1ddbca5898ab0ca753ca25',
    messagingSenderId: '749691611072',
    projectId: 'app-futebol-122ad',
    authDomain: 'app-futebol-122ad.firebaseapp.com',
    storageBucket: 'app-futebol-122ad.firebasestorage.app',
    measurementId: 'G-PXXWWQS131',
  );
}
