from machine import Pin
from utime import sleep

print("Hello, ESP34!")
led1 = Pin(12, Pin.OUT)
led2 = Pin(14, Pin.OUT)
led3 = Pin(27, Pin.OUT)
led4 = Pin(26, Pin.OUT)
led5 = Pin(25, Pin.OUT)
led6 = Pin(33, Pin.OUT)
while True:
    led1.off()
    led2.off()
    led3.on()
    led4.on()
    led5.off()
    led6.off()
    sleep(10)
    led1.off()
    led2.on()
    led3.off()
    led4.off()
    led5.on()
    led6.off()
    sleep(4)
    led1.on()
    led2.off()
    led3.off()
    led4.off()
    led5.off()
    led6.on()
    sleep(10)